sudo: false

language: node_js
node_js:
  - "4.0"
  - "6.0"

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database graphql_sequelize_test;' -U postgres

script:
  - "npm run check && npm run test-integration"

notifications:
  email: false
